import { Inter, Noto_Sans_TC } from "next/font/google";
import "./globals.css";

// 字體變數設定
export const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const notoSans = Noto_Sans_TC({
  subsets: ['latin'],
  variable: '--font-notoSans',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${notoSans.variable} ${inter.variable} `}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
